all: funding commitment revocation collateral reclaim penalty1 penalty2
funding:
	pdflatex --shell-escape funding.tex; rm funding.{aux,log,pdf}

commitment:
	pdflatex --shell-escape commitment.tex; rm commitment.{aux,log,pdf}

revocation:
	pdflatex --shell-escape revocation.tex; rm revocation.{aux,log,pdf}

collateral:
	pdflatex --shell-escape collateral.tex; rm collateral.{aux,log,pdf}

reclaim:
	pdflatex --shell-escape reclaim.tex; rm reclaim.{aux,log,pdf}

penalty1:
	pdflatex --shell-escape penalty1.tex; rm penalty1.{aux,log,pdf}

penalty2:
	pdflatex --shell-escape penalty2.tex; rm penalty2.{aux,log,pdf}
